package org.ashton.foodbank.api.entity;

import com.google.common.base.Preconditions;

/** Utility for auto-generated fields. */
public final class AutoFieldsUtil {
  private AutoFieldsUtil() {}

  /** Make sure these fields are not set as they are auto-generated by our services. */
  public static <T extends EntityMeta> void checkAutoFieldsNotSet(T newEntity, T existingEntity) {
    Preconditions.checkArgument(
        newEntity.getCreatedBy() == null
            || (existingEntity != null
                && existingEntity.getCreatedBy() != null
                && existingEntity.getCreatedBy().equals(newEntity.getCreatedBy())),
        "createdBy field will be set automatically and should not be sent in a request.");
    Preconditions.checkArgument(
        newEntity.getCreated() == null
            || (existingEntity != null
                && existingEntity.getCreated() != null
                && existingEntity.getCreated().equals(newEntity.getCreated())),
        "created field will be set automatically and should not be sent in a request.");
    checkUpdatedNotSet(newEntity);
  }

  /** Make sure these fields are not set in creation as they are auto-generated by our services. */
  public static <T extends EntityMeta> void checkAutoFieldsNotSetInCreation(T entity) {
    checkAutoFieldsNotSet(entity, null);
  }

  /** Make sure updated and updatedby are not set as they are auto-generated by our services. */
  private static <T extends EntityMeta> void checkUpdatedNotSet(T entity) {
    Preconditions.checkArgument(
        entity.getUpdatedBy() == null,
        "updatedBy field will be set automatically and should not be sent in a request.");
    Preconditions.checkArgument(
        entity.getUpdated() == null,
        "updated field will be set automatically and should not be sent in a request.");
  }
}
